name: mlops CI in flask

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  config:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.12]
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          
      - name: Configurando venv e instalando dependências
        run: |
          python -m venv venv
          source venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: verificando a execução do modelo
        run: |
          source venv/bin/activate
          python3 treinamento-modelo/treinamento-do-modelo.py
          
      - name: Subindo o server local
        run: |
          source venv/bin/activate
          python3 apis/main.py &
          sleep 5             

      - name: Testando a configuração e resposta
        run: |
          source venv/bin/activate
          curl -I http://127.0.0.1:5000/ || exit 1
          python apis/request.py --tamanho 120 --ano 2001 --garagem 2 --username ${{ secrets.FLASK_USERNAME }} --password ${{ secrets.FLASK_PASSWORD }}
          tail -n1 flask.log | grep 200
          
      - name: Kill server
        run: |
          kill $(lsof -t -i:5000)
